version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mini_edi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mini_edi_db
      MYSQL_USER: edi_user
      MYSQL_PASSWORD: edi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: mini_edi_app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: edi_user
      MYSQL_PASSWORD: edi_password
      MYSQL_DATABASE: mini_edi_db
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: python run.py

volumes:
  mysql_data:
